### ISSUE TITLE
homeのページでホームボタンやアイコンを押しても正しく表示されない

### ISSUE THREAD

**Issue by Chiharu-Hagihara** [Imaginic/imaginic.github.io#3]
最初
<img width="868" alt="Screen Shot 0003-12-11 at 5 16 44 PM" src="https://user-images.githubusercontent.com/56902613/145669693-6f45a238-3aab-4311-a386-5314bb667c4a.png">

ホームボタンプッシュ
<img width="745" alt="Screen Shot 0003-12-11 at 5 16 51 PM" src="https://user-images.githubusercontent.com/56902613/145669711-3769bfa9-167b-473f-b517-8b06db357396.png">

**Comment by m1r4i** [comment]
キャッシュが原因かも...?
(私の環境では起きなかったから...)

**Comment by Chiharu-Hagihara** [comment]
キャッシュの問題でした。
